/* SUMMARY */
SELECT * FROM FC;
SELECT * FROM RE;
SELECT * FROM MN;
SELECT * FROM MC;
SELECT * FROM CU;
SELECT * FROM OS;
SELECT * FROM OD;

/* TEAM 1
  RESTAURANT : 1123123123 / !1234QWE
  USER : TEAM1USER / @1234QWE
*/

/* TEAM 2
  RESTAURANT : 1123345123 / !1234QWE
  USER : TEAM2USER / @1234QWE
*/
/* TEAM 3
  RESTAURANT : 1125673123 / !1234QWE
  USER : TEAM3USER / @1234QWE
*/
/* TEAM 4
  RESTAURANT : 1123126783 / !1234QWE
  USER : TEAM4USER / @1234QWE
*/
/* TEAM 5
  RESTAURANT : 1123423123 / !1234QWE
  USER : TEAM5USER / @1234QWE
*/
/* TEAM 6
  RESTAURANT : 1123478823 / !1234QWE
  USER : TEAM6USER / @1234QWE
*/
/* TEAM 7
  RESTAURANT : 2155555555 / !1234QWE
  USER : TEAM7USER / @1234QWE
*/

/* plzec 시작 전 반드시 생성 할 것 */
-- AMOUNT_BY_RESTAURANT
  CREATE OR REPLACE VIEW AMOUNT_BY_RESTAURANT
  AS 
  SELECT OS.OS_RECODE AS "RECODE",
        RE.RE_NAME AS "RESTAURANT",
        OS.OS_CUID AS "CUCODE",
        TO_CHAR(OS.OS_DATE, 'YYYY-MM-DD') AS "RDATE",
        OD.OD_MNCODE AS "MENUCODE",
        MN.MN_NAME AS "MENU",
        MC.MC_PRICE AS PRICE,
        OD.OD_COUNT AS "QUANTITY"
 FROM OD INNER JOIN OS ON OD.OD_RECODE = OS.OS_RECODE AND
                          OD.OD_CUCODE = OS.OS_CUID AND
                          OD.OD_DATE = OS.OS_DATE
         INNER JOIN MC ON OD.OD_RECODE = MC.MC_RECODE AND
                          OD.OD_MNCODE = MC.MC_MNCODE
         INNER JOIN RE ON OS.OS_RECODE = RE.RE_CODE
         INNER JOIN MN ON OD.OD_MNCODE = MN.MN_CODE
 WHERE OS.OS_PROCESS = 'C';

-- GKPAVIEW
  CREATE OR REPLACE VIEW GPAVIEW
  AS 
  SELECT  OD.OD_RECODE AS "RECODE",
        OD.OD_MNCODE AS "MENUCODE",
        COUNT(OD.OD_COUNT) AS "COUNT",
        ROUND(AVG(OD.OD_GRADE),1) AS "GPA"
FROM OD 
WHERE OD.OD_GRADE != 0
GROUP BY OD.OD_RECODE, OD.OD_MNCODE;

-- MYRESERVE
  CREATE OR REPLACE VIEW MYRESERVE
  AS 
  SELECT CU.CU_ID AS "CUID",
        RE.RE_NAME AS "RENAME",       
        OD.OD_MNCODE AS "MENU",
        OD.OD_DATE AS "DATE",
        SUM(OD.OD_COUNT * MC.MC_PRICE) AS "PRICE"
 FROM OD INNER JOIN MC ON OD.OD_RECODE = MC.MC_RECODE
         INNER JOIN RE ON MC.MC_RECODE = RE.RE_CODE
         INNER JOIN CU ON OD.OD_CUCODE = CU.CU_ID
 GROUP BY RE.RE_NAME, OD.OD_MNCODE, OD.OD_DATE, CU.CU_ID;

-- REINFO
  CREATE OR REPLACE VIEW REINFO
  AS 
  SELECT RE_CODE AS RCODE,
         RE_NAME AS RNAME, 
         RE_CEO AS RCEO, 
         RE_CATE AS RCATE, 
         FC_NAME AS FCNAME, 
         RE_LOCATE AS RLOCATE
  FROM RE INNER JOIN FC ON RE.RE_CATE = FC.FC_CODE;

-- RESERVE
  CREATE OR REPLACE VIEW RESERVE
  AS 
  SELECT RE.RE_CODE AS "RECODE",
       RE.RE_NAME AS "RENAME",
       CU.CU_NAME AS "CUNAME",
       CU.CU_PHONE AS "CUPHONE",
       OS.OS_DATE AS "REDATE",
       OD.OD_MNCODE AS "MENU",
       SUM(OD.OD_COUNT * MC.MC_PRICE) AS "PRICE",
       OS.OS_PROCESS AS "PROCESS"
FROM  OD INNER JOIN OS ON OD.OD_RECODE = OS.OS_RECODE AND
                         OD.OD_DATE = OS.OS_DATE AND
                         OD.OD_CUCODE = OS.OS_CUID
      INNER JOIN CU ON OD.OD_CUCODE = CU.CU_ID
      INNER JOIN RE ON OS.OS_RECODE = RE.RE_CODE
      INNER JOIN MC ON RE.RE_CODE = MC.MC_RECODE
GROUP BY RE.RE_CODE, RE.RE_NAME, CU.CU_NAME, CU.CU_PHONE, OS.OS_PROCESS, OS.OS_DATE, OD.OD_MNCODE;

-- RESERVEDCHECK
  CREATE OR REPLACE VIEW RESERVEDCHECK
  AS 
  SELECT RE.RE_CODE AS "RECODE",
       RE.RE_NAME AS "RENAME",
       MC.MC_MNCODE AS "MNCODE",
       MN.MN_NAME AS "MNNAME",
       OS.OS_CUID AS "CUID",
       OD.OD_DATE AS "DATE",
       OD.OD_COUNT AS "QUANTITY",
       MC.MC_PRICE AS "PRICE",
       OS.OS_PROCESS AS "PROCSS"
FROM OD INNER JOIN RE ON OD.OD_RECODE = RE.RE_CODE
        INNER JOIN MC ON MC.MC_RECODE = OD.OD_RECODE
        INNER JOIN MN ON MN.MN_CODE = MC.MC_MNCODE
        INNER JOIN OS ON OD.OD_RECODE = OS.OS_RECODE;

-- RESERVEDINFO
  CREATE OR REPLACE VIEW RESERVEDINFO 
  AS 
  SELECT  OS.OS_RECODE AS "RECODE",
            RE.RE_NAME AS "RENAME",
            OS.OS_CUID AS "CUID",
            CU.CU_NAME AS "CUNAME",
            CU.CU_PHONE AS "CUPHONE",
            OS.OS_DATE AS "RDATE",
            OS.OS_PROCESS AS "PROCESS"
    FROM OS INNER JOIN RE ON OS.OS_RECODE = RE.RE_CODE
            INNER JOIN CU ON OS.OS_CUID = CU.CU_ID;

-- RESERVEINFO
  CREATE OR REPLACE VIEW RESERVEINFO AS 
  SELECT CU.CU_NAME AS "CUNAME",
        RE.RE_NAME AS "RENAME",       
        OD.OD_MNCODE AS "MENU",
        OD.OD_DATE AS "DATE",
        OD.OD_COUNT AS "COUNT",
        MC.MC_PRICE AS "PRICE"
 FROM OD INNER JOIN MC ON OD.OD_RECODE = MC.MC_RECODE
         INNER JOIN RE ON MC.MC_RECODE = RE.RE_CODE
         INNER JOIN CU ON OD.OD_CUCODE = CU.CU_ID;
         
-- RESERVELIST
  CREATE OR REPLACE VIEW RESERVELIST
  AS 
  SELECT  OD.OD_RECODE AS "RECODE",
        OD.OD_CUCODE AS "CUID",
        OD.OD_DATE AS "RDATE",
        CU.CU_NAME AS "CNAME",
        SUM(OD.OD_COUNT) AS "COUNT",
        OS.OS_PROCESS AS "PROCESS"
  FROM OD INNER JOIN CU ON OD.OD_CUCODE = CU.CU_ID
        INNER JOIN OS ON OD.OD_RECODE = OS.OS_RECODE AND
                         OD.OD_DATE = OS.OS_DATE AND
                         OD.OD_CUCODE = OS.OS_CUID
  GROUP BY OD.OD_RECODE, OD.OD_CUCODE, OD.OD_DATE, CU.CU_NAME, OS.OS_PROCESS;

-- RLISTBYDATE
  CREATE OR REPLACE VIEW RLISTBYDATE 
  AS 
  SELECT  OD.OD_RECODE AS "RECODE",
        RE.RE_NAME AS "RENAME",
        OD.OD_CUCODE AS "CUID",
        CU.CU_NAME AS "CUNAME",
        NVL(CU.CU_PHONE, 'NONE') AS "PHONE",
        OD.OD_MNCODE AS "MNCODE",
        MN.MN_NAME AS "MENU",
        OD.OD_COUNT AS "QUANTITY",
        OD.OD_DATE AS "ODDATE"
FROM OD INNER JOIN RE ON OD.OD_RECODE = RE.RE_CODE
        INNER JOIN CU ON OD.OD_CUCODE = CU.CU_ID
        INNER JOIN MN ON OD.OD_MNCODE = MN.MN_CODE;

-- SEARCHVIEW
  CREATE OR REPLACE VIEW SEARCHVIEW
  AS 
  SELECT  RE.RE_CODE AS "RECODE", 
        RE.RE_NAME AS "RESTAURANT",
        RE.RE_LOCATE AS "LOCATION",
        FC.FC_NAME AS "CATEGORY",
        MN.MN_CODE AS "MENUCODE",
        MN.MN_NAME AS "MENU",
        MC.MC_PRICE AS "PRICE",
        NVL(MC.MC_COMMENTS, ' ') AS "COMMENTS",
        RE.RE_NAME || ' ' || RE.RE_LOCATE || ' ' || MN.MN_NAME || ' ' || FC.FC_NAME || '' || MC.MC_COMMENTS AS "SWORD" 
FROM MC INNER JOIN RE ON MC.MC_RECODE = RE.RE_CODE
        INNER JOIN MN ON MC.MC_MNCODE = MN.MN_CODE
        INNER JOIN FC ON RE.RE_CATE = FC.FC_CODE;

-- SEARCHLIST
  CREATE OR REPLACE VIEW SEARCHLIST 
  AS 
  SELECT  S.RECODE AS "RECODE", 
        S.RESTAURANT AS "RESTAURANT",
        S.LOCATION AS "LOCATION",
        S.CATEGORY AS "CATEGORY",
        S.MENUCODE AS "MENUCODE",
        S.MENU AS "MENU", 
        S.PRICE AS "PRICE", 
        G.GPA * 10 AS "GPA",
        G.COUNT AS "COUNT",
        S.COMMENTS AS "COMMENTS",
        S.SWORD AS "SWORD"
FROM SEARCHVIEW S INNER JOIN GPAVIEW G
  ON S.RECODE = G.RECODE AND S.MENUCODE = G.MENUCODE;

-- TODAYSELL 
CREATE OR REPLACE VIEW TODAYSELL AS 
  SELECT RE.RE_CODE AS "RECODE",
       RE.RE_NAME AS "RENAME",
       TO_CHAR(OD.OD_DATE, 'YYYY-MM-DD') AS "REDATE",
       MN.MN_NAME AS "MENU",
       SUM(OD.OD_COUNT * MC.MC_PRICE) AS "PRICE"
FROM OD INNER JOIN RE ON OD.OD_RECODE = RE.RE_CODE
        INNER JOIN MN ON MN.MN_CODE = OD.OD_MNCODE
        INNER JOIN MC ON MC.MC_RECODE = RE.RE_CODE
        
GROUP BY RE.RE_CODE, RE.RE_NAME, OD.OD_DATE, MN.MN_NAME;


